# SignalFrame Docker Compose setup
# © 2025 CATALYSTS LABS
# Licensed under LICENSE.txt / LICENSE_COMMERCIAL.txt

version: '3.8'

services:
  php:
    image: php:8.3-fpm
    container_name: signalframe_php
    volumes:
      - ./admin:/var/www/html/admin
      - ./setup:/var/www/html/setup
      - ./api:/var/www/html/api
      - ./common:/var/www/html/common
      - ./stations:/var/www/html/stations
      - ./engine:/var/www/html/engine
      - ./themes:/var/www/html/themes
      - ./config:/var/www/html/config
      - ./logs:/var/www/html/logs
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - TZ=America/New_York  # Adjust to your timezone
    networks:
      - signalframe_net

  nginx:
    image: nginx:latest
    container_name: signalframe_nginx
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./admin:/var/www/html/admin
      - ./setup:/var/www/html/setup
      - ./api:/var/www/html/api
      - ./common:/var/www/html/common
      - ./stations:/var/www/html/stations
      - ./engine:/var/www/html/engine
      - ./themes:/var/www/html/themes
      - ./config:/var/www/html/config
      - ./logs:/var/www/html/logs
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - signalframe_net

  # Optional: Use your own Icecast stream externally or add container here:
  # icecast:
  #   image: infiniteproject/icecast
  #   container_name: signalframe_icecast
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./icecast-config:/etc/icecast2
  #   networks:
  #     - signalframe_net

networks:
  signalframe_net:
    driver: bridge
