# SignalFrame Docker Compose setup
# © 2025 CATALYSTS LABS
# Licensed under LICENSE.txt / LICENSE_COMMERCIAL.txt

version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    volumes:
      - ./www:/var/www/html

  icecast:
    image: infinityradio/icecast
    ports:
      - "8000:8000"
    environment:
      ICECAST_SOURCE_PASSWORD: change_this
      ICECAST_ADMIN_PASSWORD: change_this
      ICECAST_RELAY_PASSWORD: change_this
